import type {RoomId, UserId, GameId} from './puzzle';

// ============================================================================
// Room Event Types (Event Sourcing)
// ============================================================================

/**
 * All possible room event types
 */
export type RoomEventType = 'user_join' | 'user_leave' | 'chat_message' | 'room_settings_update';

/**
 * Base interface for all room events
 */
export interface BaseRoomEvent<T extends RoomEventType = RoomEventType> {
  type: T;
  timestamp: number;
  userId?: UserId;
}

/**
 * Event emitted when a user joins a room
 */
export interface UserJoinRoomEvent extends BaseRoomEvent<'user_join'> {
  params: {
    /** The unique identifier of the user joining the room */
    userId: UserId;
    /** The display name of the user */
    displayName: string;
  };
}

/**
 * Event emitted when a user leaves a room
 */
export interface UserLeaveRoomEvent extends BaseRoomEvent<'user_leave'> {
  params: {
    /** The unique identifier of the user leaving the room */
    userId: UserId;
  };
}

/**
 * Event emitted when a chat message is sent in a room
 */
export interface ChatMessageRoomEvent extends BaseRoomEvent<'chat_message'> {
  params: {
    /** The chat message content */
    message: string;
    /** The unique identifier of the user sending the message */
    userId: UserId;
    /** The display name of the user sending the message */
    displayName: string;
  };
}

/**
 * Event emitted when room settings are updated
 */
export interface RoomSettingsUpdateRoomEvent extends BaseRoomEvent<'room_settings_update'> {
  params: {
    /** The updated room settings as key-value pairs */
    settings: Record<string, unknown>;
  };
}

/**
 * Union type for all room events
 */
export type RoomEvent =
  | UserJoinRoomEvent
  | UserLeaveRoomEvent
  | ChatMessageRoomEvent
  | RoomSettingsUpdateRoomEvent;

// ============================================================================
// Room State
// ============================================================================

/**
 * Room state derived from events (event sourcing pattern)
 */
export interface RoomState {
  /** The unique identifier of the room */
  rid: RoomId;
  /** Array of users currently in the room */
  users: Array<{
    /** The unique identifier of the user */
    userId: UserId;
    /** The display name of the user */
    displayName: string;
    /** Timestamp when the user joined the room (Unix timestamp in milliseconds) */
    joinedAt: number;
  }>;
  /** Room settings as key-value pairs */
  settings: Record<string, unknown>;
  /** The currently active game in this room, if any */
  currentGameId?: GameId;
}

// ============================================================================
// API Request/Response Types
// ============================================================================

/**
 * Request to create a new room
 */
export interface CreateRoomRequest {
  /** Optional room ID. If not provided, a new one is generated by the backend */
  rid?: RoomId;
}

/**
 * Response after creating a room
 */
export interface CreateRoomResponse {
  /** The unique identifier of the created room */
  rid: RoomId;
}
